/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "etiquettable.h"
struct compte list_compte[50];
int nb_compte=0;

struct fruit_legume list_fruit_legume[50];
int nb_fruit_legume=0;

struct poisson list_poisson[50];
int nb_poisson=0;

struct poisson list_recette[50];
int nb_recette=0;

struct compte compte_connect;

int *
inscription_1_svc(compte *argp, struct svc_req *rqstp)
{
	list_compte[nb_compte++]=argp;
	return 1;
}

int *
connexion_1_svc(connect *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_compte; i++)
	{
		if (argp->email == list_compte[i].email && argp->mdp == list_compte[i].mdp)
		{
			compte_connect=list_compte[i];
			return 0;
		}
	}
	return 1;
}

fruit_legume *
fiche_fruit_legume_1_svc(char *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_fruit_legume; i++)
	{
		if (argp == list_fruit_legume[i].nom)
		{
			return list_fruit_legume[i];
		}
	}
	return NULL;
}

poisson *
fiche_poisson_1_svc(char *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_poisson; i++)
	{
		if (argp == list_poisson[i].nom)
		{
			return list_poisson[i];
		}
	}
	return NULL;
}

recette *
fiche_recette_1_svc(char *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_fruit_legume; i++)
	{
		if (argp == list_fruit_legume[i].nom)
		{
			return list_fruit_legume[i];
		}
	}
	return NULL;
}

compte *
fiche_user_1_svc(char *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_compte; i++)
	{
		if (argp == list_compte[i].email)
		{
			return list_compte[i];
		}
	}
	return 1;
}

int *
deconnexion_1_svc(void *argp, struct svc_req *rqstp)
{
	compte_connect=NULL;
}

int *
ini_1_svc(ini *argp, struct svc_req *rqstp)
{
	
	struct fruit_legume fruit_legume_ini =
	{
		argp->nom_fruit_legume,
		NULL,
		"France",
		"jsp",
		"jsp",
		"jsp",
		50000,
		1
	};
	struct poisson poisson_ini
	{
		argp->nom_poisson,
		"jsp",
		"jsp",
		"jsp",
		"jsp",
		50000,
		50000,
		50000,
		0,
	};
	struct recette recette_ini
	{
		argp->nom_recette,
		0,
		0,
		0,
		0,
		"jsp",
		NULL,
		NULL,
		"jsp",
		NULL
	};
	struct compte compte2_ini{argp->email,"1234","toto","tutu","15/04/2024","M",1,0};
	
	
	list_compte[nb_compte++]=argp->compte_ini;
	list_fruit_legume[nb_fruit_legume++]=fruit_legume_ini;
	list_poisson[nb_poisson++]=poisson_ini;
	list_recette[nb_recette++]=recette_ini;
	list_compte[nb_compte++]=compte2_ini;

	return 1
}