/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "etiquettable.h"

bool_t
xdr_compte (XDR *xdrs, compte *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->photo, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->email, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->mdp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->prenom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->date_naissance, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->genre, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->condition_general))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->newsletter))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->location, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->profil_allimentaire, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mois (XDR *xdrs, mois *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->janvier))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fevrier))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mars))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->avril))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->juin))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->juillet))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aout))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->septembre))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->novembre))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->decembre))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->janvier);
			IXDR_PUT_LONG(buf, objp->fevrier);
			IXDR_PUT_LONG(buf, objp->mars);
			IXDR_PUT_LONG(buf, objp->avril);
			IXDR_PUT_LONG(buf, objp->juin);
			IXDR_PUT_LONG(buf, objp->juillet);
			IXDR_PUT_LONG(buf, objp->aout);
			IXDR_PUT_LONG(buf, objp->septembre);
			IXDR_PUT_LONG(buf, objp->novembre);
			IXDR_PUT_LONG(buf, objp->decembre);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 10 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->janvier))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->fevrier))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mars))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->avril))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->juin))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->juillet))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aout))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->septembre))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->novembre))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->decembre))
				 return FALSE;
		} else {
			objp->janvier = IXDR_GET_LONG(buf);
			objp->fevrier = IXDR_GET_LONG(buf);
			objp->mars = IXDR_GET_LONG(buf);
			objp->avril = IXDR_GET_LONG(buf);
			objp->juin = IXDR_GET_LONG(buf);
			objp->juillet = IXDR_GET_LONG(buf);
			objp->aout = IXDR_GET_LONG(buf);
			objp->septembre = IXDR_GET_LONG(buf);
			objp->novembre = IXDR_GET_LONG(buf);
			objp->decembre = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->janvier))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fevrier))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mars))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->avril))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->juin))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->juillet))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aout))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->septembre))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->novembre))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->decembre))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_fruit_legume (XDR *xdrs, fruit_legume *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_mois (xdrs, &objp->mois_saison))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->pays, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->choisir, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->conserver, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->calories))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sucres))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_poisson (XDR *xdrs, poisson *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->provenance_recommander, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->provenance_eviter, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->choisir, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->sante_bienfait, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sante_calories))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sante_proteine))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sante_mat_grasses))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->menace))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->sante_calories);
			IXDR_PUT_LONG(buf, objp->sante_proteine);
			IXDR_PUT_LONG(buf, objp->sante_mat_grasses);
			IXDR_PUT_LONG(buf, objp->menace);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->provenance_recommander, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->provenance_eviter, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->choisir, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->sante_bienfait, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->sante_calories))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sante_proteine))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->sante_mat_grasses))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->menace))
				 return FALSE;
		} else {
			objp->sante_calories = IXDR_GET_LONG(buf);
			objp->sante_proteine = IXDR_GET_LONG(buf);
			objp->sante_mat_grasses = IXDR_GET_LONG(buf);
			objp->menace = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->provenance_recommander, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->provenance_eviter, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->choisir, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->sante_bienfait, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sante_calories))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sante_proteine))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sante_mat_grasses))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->menace))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_recette (XDR *xdrs, recette *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->temp))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->budget))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->calories))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->saison))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nb_pers))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->temp);
		IXDR_PUT_LONG(buf, objp->budget);
		IXDR_PUT_LONG(buf, objp->calories);
		IXDR_PUT_LONG(buf, objp->saison);
		IXDR_PUT_LONG(buf, objp->nb_pers);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->allergene, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fruits_legumes, 50,
			sizeof (fruit_legume), (xdrproc_t) xdr_fruit_legume))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->poissons, 50,
			sizeof (poisson), (xdrproc_t) xdr_poisson))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->recette, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_compte (xdrs, &objp->createur))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->temp))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->budget))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->calories))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->saison))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->nb_pers))
				 return FALSE;

		} else {
		objp->temp = IXDR_GET_LONG(buf);
		objp->budget = IXDR_GET_LONG(buf);
		objp->calories = IXDR_GET_LONG(buf);
		objp->saison = IXDR_GET_LONG(buf);
		objp->nb_pers = IXDR_GET_LONG(buf);
		}
		 if (!xdr_pointer (xdrs, (char **)&objp->allergene, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fruits_legumes, 50,
			sizeof (fruit_legume), (xdrproc_t) xdr_fruit_legume))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->poissons, 50,
			sizeof (poisson), (xdrproc_t) xdr_poisson))
			 return FALSE;
		 if (!xdr_pointer (xdrs, (char **)&objp->recette, sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_compte (xdrs, &objp->createur))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->temp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->budget))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->calories))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->saison))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_pers))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->allergene, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fruits_legumes, 50,
		sizeof (fruit_legume), (xdrproc_t) xdr_fruit_legume))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->poissons, 50,
		sizeof (poisson), (xdrproc_t) xdr_poisson))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->recette, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_compte (xdrs, &objp->createur))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connection (XDR *xdrs, connection *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->email, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->mdp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_init (XDR *xdrs, init *objp)
{
	register int32_t *buf;

	 if (!xdr_compte (xdrs, &objp->compte_ini))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nom_fruit_legume, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nom_poisson, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nom_recette, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->email, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
