/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "etiquettable.h"

struct compte list_compte[50];
int nb_compte = 0;

struct fruit_legume list_fruit_legume[50];
int nb_fruit_legume = 0;

struct poisson list_poisson[50];
int nb_poisson = 0;

struct recette list_recette[50];
int nb_recette = 0;


struct compte compte_connect;


int *
ini_1_svc(init *argp, struct svc_req *rqstp)
{
	static int  result=1;

	//compte
	
	struct compte compte1 = {
    "https://example.com/photo1.jpg", // photo
    "utilisateur1@example.com",      // email
    "mdp1234",                        // mdp
    "Jean",                           // prenom
    "Dupont",                         // nom
    "1990-05-15",                     // date_naissance
    "Homme",                          // genre
    1,                                // condition_general (1 = ok, 0 = problème)
    1,                                // newsletter (1 = abonné, 0 = non abonné)
    "Paris, France",                  // location
    "Végétarien"                      // profil_allimentaire
	};
	struct compte compte2 = {
    	"https://example.com/photo2.jpg",
    	"utilisateur2@example.com",
    	"mdp5678",
    	"Marie",
    	"Lemoine",
    	"1985-08-22",
    	"Femme",
    	1,
    	0,
    	"Lyon, France",
    	"Omnivore"
	};
	
	//struct mois
	struct mois mois_saison_fruit = {
    1, // janvier
    1, // mars
    1, // avril
    0, // mai
    0, // juin
    0, // juillet
    0, // août
    0, // septembre
    0, // novembre
    1  // décembre
	};
	
	//struct fruit_legume
	struct fruit_legume pomme = {
    "Pomme",                          // nom
    mois_saison_fruit,                 // mois_saison
    "France",                          // pays
    "Choisir des pommes fermes et non abîmées.",  // choisir
    "Conserver dans un endroit frais et sec.",    // conserver
    52,                                // calories
    10                                 // sucres
	};
	struct fruit_legume tomate = {
    	"Tomate",
    	mois_saison_fruit,
    	"Espagne",
    	"Choisir des tomates bien rouges.",
    	"Conserver au réfrigérateur si elles sont mûres.",
    	18,
    	3
	};
	
	
	//struct poisson
	 struct poisson thon = {
    "Thon",                           // nom
    "Océan Atlantique",                // provenance_recommander
    "Mer Méditerranée",                // provenance_eviter
    "Choisir un thon pêché de manière durable.",
    "Riche en protéines et oméga-3.",
    132,                               // calories
    28,                                // protéines
    5,                                 // matières grasses
    0                                  // menace (0 = non menacé, 1 = menacé)
	};
	
	struct poisson saumon = {
    	"Saumon",
    	"Mer de Norvège",
    	"Océan Atlantique",
    	"Préférer le saumon sauvage.",
    	"Excellente source de vitamine D.",
    	208,
    	20,
    	13,
    	1
	};
	
	
	struct recette recette1 = {
    "Salade de fruits",                // nom
    15,                                // temp (15 minutes)
    10,                                // budget (en euros)
    120,                               // calories
    1,                                 // saison (1 = printemps)
    2,                                 // nb_pers (2 personnes)
    "Aucune",                          // allergene
    {pomme, tomate},                   // fruits_legumes
    {thon},                            // poissons
    "Mélangez des pommes ", // recette
    compte1                             // createur
	};
	
	struct recette recette2 = {
    	"Poisson grillé",                  // nom
    	30,                                // temp (30 minutes)
    	20,                                // budget
    	250,                               // calories
    	2,                                 // saison (2 = été)
    	4,                                 // nb_pers
    	"Poisson",                         // allergene
    	{pomme},                           // fruits_legumes
    	{saumon},                          // poissons
    	"Grillez le saumon ", // recette
    	compte2                             // createur
	};

	// Insertion dans les tableaux
	list_compte[nb_compte++] = compte1;
	list_compte[nb_compte++] = compte2;
	//printf("compte ajouter : 1:%s 2:%s\n",list_compte[0].nom,list_compte[1].nom);
	
	list_fruit_legume[nb_fruit_legume++] = pomme;
	list_fruit_legume[nb_fruit_legume++] = tomate;
	//printf("fruit_legume ajouter : 1:%s 2:%s\n",list_fruit_legume[0].nom,list_fruit_legume[1].nom);
	
	list_poisson[nb_poisson++] = thon;
	list_poisson[nb_poisson++] = saumon;
	//printf("poisson ajouter : 1:%s 2:%s\n",list_poisson[0].nom,list_poisson[1].nom);
	
	list_recette[nb_recette++] = recette1;
	list_recette[nb_recette++] = recette2;
	//printf("recette ajouter : 1:%s 2:%s\n",list_recette[0].nom,list_recette[1].nom);

	printf("initialisation terminer\n");
	return &result;
}

int *
inscription_1_svc(compte *argp, struct svc_req *rqstp)
{
	static int  result=1;
	
	list_compte[nb_compte++] = *argp;
	printf("compte %s inscrit\n",argp->nom);
	return &result;
}

int *
connexion_1_svc(connection *argp, struct svc_req *rqstp)
{
	static int  result=1;

	for (size_t i = 0; i < nb_compte; i++)
    {

        if (strcmp(argp->email, list_compte[i].email) == 0 && strcmp(argp->mdp, list_compte[i].mdp) == 0)
        {
            compte_connect = list_compte[i];
            result=0;
            printf("compte %s conecter\n",compte_connect.nom);
            return &result;
        }
    }

	return &result;
}

fruit_legume *
fiche_fruit_legume_1_svc(char *argp, struct svc_req *rqstp)
{
	static fruit_legume  result;
	
	printf("argp : %s\n",argp);
	for (size_t i = 0; i < nb_fruit_legume; i++)
    {
    	printf("argp : %s/%s | %d\n",argp,list_fruit_legume[i].nom,strcmp(argp, list_fruit_legume[i].nom));
        if (strcmp(argp, list_fruit_legume[i].nom) == 0)
        {
        	printf("fruit_legume %s trouver et retourner\n",list_fruit_legume[i].nom);
            return &list_fruit_legume[i];
        }
    }

	return &result;
}

poisson *
fiche_poisson_1_svc(char *argp, struct svc_req *rqstp)
{
	for (size_t i = 0; i < nb_poisson; i++)
    {
        if (strcmp(argp, list_poisson[i].nom) == 0)
        {
        	printf("fiche_poisson %s trouver et retourner\n",list_poisson[i].nom);
            return &list_poisson[i];
        }
    }
    return NULL;
}

recette *
fiche_recette_1_svc(char *argp, struct svc_req *rqstp)
{
	static recette  result;

	/*
	 * insert server code here
	 */

	return &result;
}

compte *
fiche_user_1_svc(char *argp, struct svc_req *rqstp)
{
	static compte  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
deconnexion_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
