/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ETIQUETTABLE_H_RPCGEN
#define _ETIQUETTABLE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct compte {
	char photo[50];
	char email[50];
	char mdp[50];
	char prenom[50];
	char nom[50];
	char date_naissance[50];
	char genre[50];
	int condition_general;
	int newsletter;
	char location[50];
	char profil_allimentaire[50];
};
typedef struct compte compte;

struct mois {
	int janvier;
	int fevrier;
	int mars;
	int avril;
	int juin;
	int juillet;
	int aout;
	int septembre;
	int novembre;
	int decembre;
};
typedef struct mois mois;

struct fruit_legume {
	char nom[50];
	mois mois_saison;
	char pays[50];
	char choisir[50];
	char conserver[50];
	int calories;
	int sucres;
};
typedef struct fruit_legume fruit_legume;

struct poisson {
	char nom[50];
	char provenance_recommander[50];
	char provenance_eviter[50];
	char choisir[50];
	char sante_bienfait[50];
	int sante_calories;
	int sante_proteine;
	int sante_mat_grasses;
	int menace;
};
typedef struct poisson poisson;

struct recette {
	char nom[50];
	int temp;
	int budget;
	int calories;
	int saison;
	int nb_pers;
	char allergene[50];
	fruit_legume fruits_legumes[50];
	poisson poissons[50];
	char recette[50];
	struct compte createur;
};
typedef struct recette recette;

struct connection {
	char email[50];
	char mdp[50];
};
typedef struct connection connection;

struct init {
	compte compte_ini;
	char nom_fruit_legume[50];
	char nom_poisson[50];
	char nom_recette[50];
	char email[50];
};
typedef struct init init;

#define ETIQUETABLEPROG 0x23456789
#define ETIQUETABLEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ini 1
extern  int * ini_1(init *, CLIENT *);
extern  int * ini_1_svc(init *, struct svc_req *);
#define inscription 2
extern  int * inscription_1(compte *, CLIENT *);
extern  int * inscription_1_svc(compte *, struct svc_req *);
#define connexion 3
extern  int * connexion_1(connection *, CLIENT *);
extern  int * connexion_1_svc(connection *, struct svc_req *);
#define fiche_fruit_legume 4
extern  fruit_legume * fiche_fruit_legume_1(char *, CLIENT *);
extern  fruit_legume * fiche_fruit_legume_1_svc(char *, struct svc_req *);
#define fiche_poisson 5
extern  poisson * fiche_poisson_1(char *, CLIENT *);
extern  poisson * fiche_poisson_1_svc(char *, struct svc_req *);
#define fiche_recette 6
extern  recette * fiche_recette_1(char *, CLIENT *);
extern  recette * fiche_recette_1_svc(char *, struct svc_req *);
#define fiche_user 7
extern  compte * fiche_user_1(char *, CLIENT *);
extern  compte * fiche_user_1_svc(char *, struct svc_req *);
#define deconnexion 8
extern  int * deconnexion_1(void *, CLIENT *);
extern  int * deconnexion_1_svc(void *, struct svc_req *);
extern int etiquetableprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ini 1
extern  int * ini_1();
extern  int * ini_1_svc();
#define inscription 2
extern  int * inscription_1();
extern  int * inscription_1_svc();
#define connexion 3
extern  int * connexion_1();
extern  int * connexion_1_svc();
#define fiche_fruit_legume 4
extern  fruit_legume * fiche_fruit_legume_1();
extern  fruit_legume * fiche_fruit_legume_1_svc();
#define fiche_poisson 5
extern  poisson * fiche_poisson_1();
extern  poisson * fiche_poisson_1_svc();
#define fiche_recette 6
extern  recette * fiche_recette_1();
extern  recette * fiche_recette_1_svc();
#define fiche_user 7
extern  compte * fiche_user_1();
extern  compte * fiche_user_1_svc();
#define deconnexion 8
extern  int * deconnexion_1();
extern  int * deconnexion_1_svc();
extern int etiquetableprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_compte (XDR *, compte*);
extern  bool_t xdr_mois (XDR *, mois*);
extern  bool_t xdr_fruit_legume (XDR *, fruit_legume*);
extern  bool_t xdr_poisson (XDR *, poisson*);
extern  bool_t xdr_recette (XDR *, recette*);
extern  bool_t xdr_connection (XDR *, connection*);
extern  bool_t xdr_init (XDR *, init*);

#else /* K&R C */
extern bool_t xdr_compte ();
extern bool_t xdr_mois ();
extern bool_t xdr_fruit_legume ();
extern bool_t xdr_poisson ();
extern bool_t xdr_recette ();
extern bool_t xdr_connection ();
extern bool_t xdr_init ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ETIQUETTABLE_H_RPCGEN */
