/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "etiquettable.h"


void
etiquetableprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	init  ini_1_arg;
	int  *result_2;
	struct compte inscription_1_arg = {
    "https://example.com/photo.jpg",  // photo
    "utilisateur3@example.com",      // email
    "mdp1234",                        // mdp
    "Jean",                           // prenom
    "Dupont",                         // nom
    "1990-05-15",                     // date_naissance
    "Homme",                          // genre
    1,                                // condition_general (1 = ok)
    1,                                // newsletter (1 = abonné)
    "Paris, France",                  // location
    "Végétarien"                      // profil_allimentaire
};

	int  *result_3;
	connection  connexion_1_arg= {
    "utilisateur3@example.com",
    "mdp1234",
    };
	fruit_legume  *result_4;
	char  fiche_fruit_legume_1_arg="Pomme";
	poisson  *result_5;
	char  fiche_poisson_1_arg="Saumon";
	recette  *result_6;
	char  fiche_recette_1_arg="Poisson grillé";
	compte  *result_7;
	char  fiche_user_1_arg= "utilisateur2@example.com";
	int  *result_8;
	char *deconnexion_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ETIQUETABLEPROG, ETIQUETABLEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	fiche_fruit_legume_1_arg= "pomme";
	fiche_poisson_1_arg ="truite";
	fiche_recette_1_arg ="chesse burger";
	fiche_user_1_arg = "toto@test.com";


	result_1 = ini_1(&ini_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test init result : %ls \n",result_1);
	
	
	result_2 = inscription_1(&inscription_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test inscription result : %ls \n",result_2);
	
	result_3 = connexion_1(&connexion_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test connexion result : %ls \n",result_3);
	
	result_4 = fiche_fruit_legume_1(&fiche_fruit_legume_1_arg, clnt);
	if (result_4 == (fruit_legume *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test fiche_fruit_legume result : nom: %s / pays producteur: %s \n",result_4->nom,result_4->pays);
	
	
	result_5 = fiche_poisson_1(&fiche_poisson_1_arg, clnt);
	if (result_5 == (poisson *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test fiche_poisson result : nom: %s \n",result_5->nom);
	
	
	result_6 = fiche_recette_1(&fiche_recette_1_arg, clnt);
	if (result_6 == (recette *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test fiche_recette result : nom: %s \n",result_6->nom);
	
	
	result_7 = fiche_user_1(&fiche_user_1_arg, clnt);
	if (result_7 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test connexion result : mail:%s nom:%s prenom: %s \n",result_7->email,result_7->nom,result_7->prenom);
	
	
	result_8 = deconnexion_1((void*)&deconnexion_1_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("test connexion result : %ls \n",result_8);
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	etiquetableprog_1 (host);
exit (0);
}
